name: Enhancement / New Feature Request 💡
description: Suggest an enhancement or new feature
title: "Enhancement Request"
labels: ["enhancement", "needs triage"]
assignees: Timthreetwelve
body:
  - type: markdown
    attributes:
      value: If you have an idea for a feature or enhancement that would make the app better, tell me about it
  - type: input
    id: summary
    attributes:
      label: Brief summary of your request
      description: Enter a short description
    validations:
      required: true
  - type: textarea
    id: request
    attributes:
      label: Request details
      description: Tell me what's on your mind
    validations:
      required: true
