name: Enhancement / New Feature Request 💡
description: Suggest an enhancement or new feature
title: "Enhancement Request"
labels: ["enhancement", "needs triage"]
assignees: Timthreetwelve
body:
  - type: markdown
    attributes:
      value: Introduction text goes here
  - type: textarea
    id: summary
    attributes:
      label: Brief summary of your request
      description: Enter a short description
    validations:
      required: true
